## Numpy

In [1]:
import numpy as np
import sys

In [17]:
a = np.array([1,2,3])
b= np.array([[1,2,3,],[4,5,6,]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
#get dimension
b.ndim

2

In [4]:
#get shape
b.shape

(2, 3)

In [5]:
#get type
a.dtype

dtype('int32')

#getting variables

In [6]:
b[1,2]

np.int64(6)

In [7]:
b[0,0]

np.int64(1)

In [19]:
b = np.array([[[1,3],[3,4]],[[9,8],[3,0]]])
print (b)

[[[1 3]
  [3 4]]

 [[9 8]
  [3 0]]]


In [20]:
b[0,1,1]

np.int64(4)

In [24]:
b[:,1]

array([[3, 4],
       [3, 0]])

In [26]:
#replace
b[:,1] = [[0,0],[1,1]]
print(b)

[[[1 3]
  [0 0]]

 [[9 8]
  [1 1]]]
